apiVersion: v1
kind: Service
metadata:
  name: uuid-nodeport-service
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30000
  selector:
    app: uuid-generator-frontend
